// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rira_Task.Data;

#nullable disable

namespace Rira_Task.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rira_Task.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category1",
                            Name = "Product A",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category1",
                            Name = "Product B",
                            Price = 150m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category2",
                            Name = "Product C",
                            Price = 120m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Category3",
                            Name = "Product D",
                            Price = 200m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Category1",
                            Name = "Product E",
                            Price = 80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
